/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/users": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Create an Unclaimed User
         * @description Creates a User with no credentials attached and a generated Handle, and sets the cookie that recognises this browser as them on later visits. Nothing is asked of the visitor.
         *
         *     A browser that already holds a valid cookie is told who it is instead, with 200 — so a retry, a double submit or a second tab cannot strand the Runs the first User already has.
         */
        post: operations["create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/users/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Read the User this browser is
         * @description Returns the User the request's cookie identifies. 404 means this browser has never been here, or was here longer ago than the cookie lasts — the caller's cue to create one.
         */
        get: operations["me"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Report the backend's status and that of its dependencies
         * @description Returns 200 when every dependency is reachable and 503 when any is not, so an uptime check can rely on the status code alone rather than parsing the body.
         */
        get: operations["health"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** @description Anyone who has played, whether or not they have Claimed */
        User: {
            /**
             * Format: uuid
             * @description Stable identifier
             * @example 3f1c0b1a-5c2e-4d3b-9f8a-1e2d3c4b5a69
             */
            id: string;
            /**
             * @description The User's Handle
             * @example PERCOLATING_FERRET
             */
            handle: string;
            /**
             * @description Whether credentials have been attached to this User
             * @example false
             */
            claimed: boolean;
        };
        /** @description The backend's own status and that of its dependencies */
        HealthStatus: {
            /**
             * @description Overall status
             * @example UP
             * @enum {string}
             */
            status: "UP" | "DEGRADED";
            /**
             * @description PostgreSQL connectivity
             * @example UP
             * @enum {string}
             */
            database: "UP" | "DEGRADED";
            /**
             * @description Running build version
             * @example 0.0.1-SNAPSHOT
             */
            version: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: {
                gmc_recognition?: string;
            };
        };
        requestBody?: never;
        responses: {
            /** @description This browser was already someone, and still is */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["User"];
                };
            };
            /** @description The Unclaimed User that was created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["User"];
                };
            };
        };
    };
    me: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: {
                gmc_recognition?: string;
            };
        };
        requestBody?: never;
        responses: {
            /** @description The User this browser is recognised as */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["User"];
                };
            };
            /** @description This browser is nobody yet */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    health: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Every dependency is reachable */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthStatus"];
                };
            };
            /** @description At least one dependency is unreachable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthStatus"];
                };
            };
        };
    };
}
