/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/users": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Create an Unclaimed User
         * @description Creates a User with no credentials attached and a generated Handle, and sets the cookie that recognises this browser as them on later visits. Nothing is asked of the visitor.
         *
         *     A browser that already holds a valid cookie is told who it is instead, with 200 — so a retry, a double submit or a second tab cannot strand the Runs the first User already has.
         */
        post: operations["create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/typing-runs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Submit a finished Run for Verification
         * @description Takes raw data — the text as typed, the keystroke count, the two timestamps — and recomputes WPM and Accuracy from it. The request body has nowhere to put a client-computed metric, because none would be believed (ADR-0003).
         *
         *     A refusal is 422 with a machine-readable reason, not a 400: the request was well formed and was understood, and it is the Run that did not survive.
         */
        post: operations["submit"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/solve-runs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Submit a finished Solve Run to be judged
         * @description Takes the lines that were written, assembles them with the Pattern's Scaffold, and has the judge execute the result against every one of the Pattern's tests. The Verdict comes back from that execution; the duration and the WPM are recomputed from the raw submission (ADR-0003).
         *
         *     A Failed Verdict is a 201. The Solve Run happened, it is recorded, and it belongs to the player — a Solve Run can fail, which is the difference between it and a Typing Run (ADR-0006).
         *
         *     422 is a submission that was not recorded at all, with the reason. 503 is the judge being unreachable: no Verdict exists, nothing about the submitted source can be concluded, and the Issue is left unspent so the same lines can be sent again.
         */
        post: operations["submit_1"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/patterns/{slug}/challenges": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Be handed this Pattern to solve
         * @description Records an Issue against the User — who got what, when, and until when — and returns the Pattern with its Scaffold and Example Tests.
         *
         *     Unlike a Passage, the player names which one. There is nothing to shop for: a Pattern is a technique to practise, not a score to farm.
         *
         *     Asking again abandons whatever Challenge the User was holding, in either Discipline, so nobody can hold several at once and submit whichever went best (ADR-0003). The window is flat rather than scaled by length: a Pattern is answered by thinking, and there is nothing about it to time by the character.
         */
        post: operations["request"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/patterns/activations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Run the activation gate over every Pattern awaiting it
         * @description Assembles each inactive Pattern's reference solution with its Scaffold exactly as a player's submission would be, has the judge execute it, and activates the Pattern only if the Verdict is Passed and the judge ran as many tests as the Pattern has.
         *
         *     That second condition is not a formality. The judge compiles its catalogue into its binary and is deployed separately from the database, so the two can skew — and a judge running an older copy of a Pattern would answer Passed against fewer tests than the curator wrote, which is true and useless.
         *
         *     Answers 200 whatever happened. A Pattern that did not pass is not an error in this request; it is the gate doing its job, and the body says so per Pattern. Already-activated Patterns are not re-judged and are absent from the answer.
         */
        post: operations["activate"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/challenges": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Be handed a Passage to transcribe
         * @description Records an Issue against the User — who got what, when, and until when — and returns the Passage. Which Passage arrives is the server's choice.
         *
         *     Asking again abandons the Challenge the User was holding, so a player can skip a Passage they do not fancy, and nobody can hold several at once and submit whichever went best (ADR-0003).
         */
        post: operations["request_1"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/users/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Read the User this browser is
         * @description Returns the User the request's cookie identifies. 404 means this browser has never been here, or was here longer ago than the cookie lasts — the caller's cue to create one.
         */
        get: operations["me"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/patterns": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Browse the Patterns that can be played
         * @description Every activated Pattern — by Family, then by Seniority, then by name — optionally narrowed to one Family and one Seniority. Each carries its prompt and its Example Tests, so a player can read the contract they will be judged against before starting.
         *
         *     Inactive Patterns are absent rather than listed as unavailable. A Pattern is inactive because nobody has yet proved its tests are correct, and offering one would be offering a Challenge that might be unwinnable.
         *
         *     Hidden Tests are not here, and there is no endpoint that serves them. They live in the judge's own binary (ADR-0005), and their failure is only ever reported to a player as a count.
         */
        get: operations["browse"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Report the backend's status and that of its dependencies
         * @description Returns 200 when every dependency is reachable and 503 when any is not, so an uptime check can rely on the status code alone rather than parsing the body.
         */
        get: operations["health"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** @description Anyone who has played, whether or not they have Claimed */
        User: {
            /**
             * Format: uuid
             * @description Stable identifier
             * @example 3f1c0b1a-5c2e-4d3b-9f8a-1e2d3c4b5a69
             */
            id: string;
            /**
             * @description The User's Handle
             * @example PERCOLATING_FERRET
             */
            handle: string;
            /**
             * @description Whether credentials have been attached to this User
             * @example false
             */
            claimed: boolean;
        };
        /** @description The raw data a finished Run is verified from */
        TypingRunSubmission: {
            /**
             * Format: uuid
             * @description The Issue this Run answers
             */
            issueId: string;
            /** @description The text as typed, in full */
            typedText: string;
            /**
             * Format: int32
             * @description Total character keystrokes, mistakes included
             * @example 312
             */
            keystrokes: number;
            /**
             * Format: date-time
             * @description The client's clock at the first keystroke
             */
            startedAt: string;
            /**
             * Format: date-time
             * @description The client's clock at the last keystroke
             */
            completedAt: string;
        };
        /** @description A completed and verified Run against a Passage */
        TypingRun: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            passageId: string;
            /**
             * @description One of the three ways to play
             * @enum {string}
             */
            discipline: "QUOTES" | "PROSE" | "CODE";
            /**
             * @description Correct characters over five, per minute, computed by the server
             * @example 78.4
             */
            wpm: number;
            /**
             * @description Correct keystrokes over total keystrokes, as a percentage
             * @example 99.1
             */
            accuracy: number;
            /**
             * Format: int32
             * @description How long the Run took
             * @example 31240
             */
            elapsedMillis: number;
            /**
             * Format: int32
             * @description Total character keystrokes, mistakes included
             * @example 312
             */
            keystrokes: number;
            /**
             * Format: int32
             * @description Characters of the Passage the final text got right
             * @example 309
             */
            correctCharacters: number;
            /**
             * Format: int32
             * @description Keystrokes that were not correct characters
             * @example 3
             */
            errors: number;
            /** Format: date-time */
            completedAt: string;
        };
        /** @description A submitted Run that was not recorded, and why */
        Rejection: {
            /**
             * @description Why a submitted Run was not recorded
             * @enum {string}
             */
            reason: "NO_SUCH_ISSUE" | "ISSUE_EXPIRED" | "ISSUE_ALREADY_USED" | "ISSUE_SUPERSEDED" | "PASSAGE_MISMATCH" | "IMPOSSIBLE_DURATION" | "IMPLAUSIBLE_KEYSTROKES" | "IMPLAUSIBLE_SPEED";
            /**
             * @description Human-readable restatement of the reason
             * @example The typed text does not correspond to the Passage that was issued.
             */
            explanation: string;
        };
        /** @description The raw data a finished Solve Run is judged and verified from */
        SolveRunSubmission: {
            /**
             * Format: uuid
             * @description The Issue this Solve Run answers
             */
            issueId: string;
            /**
             * @description The lines written below the Scaffold, exactly as typed
             * @example return []
             */
            source: string;
            /**
             * Format: int32
             * @description Every character key pressed, including ones later deleted
             * @example 180
             */
            keystrokes: number;
            /**
             * Format: date-time
             * @description The client's clock at the first keystroke
             */
            startedAt: string;
            /**
             * Format: date-time
             * @description The client's clock when the Solve Run was submitted
             */
            completedAt: string;
        };
        /** @description A completed and judged Run against a Pattern */
        SolveRun: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            patternId: string;
            /** @example hash-map-seen-lookup */
            patternSlug: string;
            /** @enum {string} */
            verdict: "passed" | "failed" | "timeout" | "error";
            /**
             * Format: int32
             * @example 6
             */
            testsPassed: number;
            /**
             * Format: int32
             * @example 6
             */
            testsTotal: number;
            /**
             * Format: int32
             * @description How long the Solve Run took, as verified
             * @example 48210
             */
            elapsedMillis: number;
            /**
             * Format: int32
             * @description Total character keystrokes
             * @example 180
             */
            keystrokes: number;
            /**
             * @description Every submitted character over five, per minute — a secondary reading
             * @example 41.2
             */
            wpm: number;
            /** Format: date-time */
            completedAt: string;
        };
        /** @description A Solve Run that could not be judged. No Run was recorded and the Challenge is still live */
        Unjudged: {
            /** @example The judge could not be reached. Your Challenge is still yours. */
            explanation: string;
        };
        /** @description A test case shown to the player before they start */
        ExampleTest: {
            /**
             * @description What the case is about
             * @example the pair is the first two numbers
             */
            name: string;
            /**
             * @description The call the submitted source must satisfy
             * @example pair_sum([2, 7, 11, 15], 9)
             */
            call: string;
            /**
             * @description The answer the call has to produce
             * @example [
             *       0,
             *       1
             *     ]
             */
            expected: string;
        };
        /** @description A Pattern to solve, as the player is shown it */
        Pattern: {
            /** Format: uuid */
            id: string;
            /**
             * @description Stable identifier, also what the judge knows this Pattern by
             * @example hash-map-seen-lookup
             */
            slug: string;
            /** @example Store what you've seen, look up what you need */
            name: string;
            /**
             * @description The grouping a Pattern belongs to
             * @enum {string}
             */
            family: "HASH_MAP" | "TWO_POINTERS" | "SLIDING_WINDOW" | "STACK" | "HEAP" | "BINARY_SEARCH" | "GRAPH" | "DYNAMIC_PROGRAMMING";
            /**
             * @description The difficulty band of a Challenge
             * @enum {string}
             */
            seniority: "JUNIOR" | "SENIOR" | "PRINCIPAL";
            /** @description The technique and what to do with it, in the player's words */
            prompt: string;
            /**
             * @description The read-only lines above the editable region
             * @example def pair_sum(numbers, target):
             */
            scaffold: string;
            exampleTests: components["schemas"]["ExampleTest"][];
        };
        /** @description A Pattern to solve, and the Issue that recorded it going out */
        SolveChallenge: {
            /**
             * Format: uuid
             * @description What the client hands back when the Solve Run is submitted
             */
            issueId: string;
            pattern: components["schemas"]["Pattern"];
            /**
             * Format: date-time
             * @description After this moment the Challenge can no longer be answered
             */
            expiresAt: string;
        };
        /** @description What the activation gate made of one Pattern */
        PatternActivation: {
            /** @example hash-map-seen-lookup */
            slug: string;
            activated: boolean;
            /**
             * @description What happened, in a sentence
             * @example The reference solution passed all 6 tests.
             */
            explanation: string;
        };
        /** @description A request for a Challenge in one Discipline */
        ChallengeRequest: {
            /**
             * @description One of the three ways to play
             * @enum {string}
             */
            discipline: "QUOTES" | "PROSE" | "CODE";
        };
        /** @description A Passage to transcribe, and the Issue that recorded it going out */
        Challenge: {
            /** Format: uuid */
            issueId: string;
            passage: components["schemas"]["Passage"];
            /**
             * Format: date-time
             * @description After this moment the Challenge can no longer be answered
             */
            expiresAt: string;
        };
        /** @description A fixed piece of text to be transcribed */
        Passage: {
            /** Format: uuid */
            id: string;
            /**
             * @description One of the three ways to play
             * @enum {string}
             */
            discipline: "QUOTES" | "PROSE" | "CODE";
            /**
             * @description The text to transcribe, printable ASCII throughout
             * @example Call me Ishmael.
             */
            text: string;
            /**
             * @description Who said or wrote it
             * @example Herman Melville, Moby-Dick, 1851
             */
            attribution: string;
            /**
             * Format: int32
             * @description How many characters the text is
             * @example 302
             */
            characterCount: number;
        };
        /** @description The backend's own status and that of its dependencies */
        HealthStatus: {
            /**
             * @description Overall status
             * @example UP
             * @enum {string}
             */
            status: "UP" | "DEGRADED";
            /**
             * @description PostgreSQL connectivity
             * @example UP
             * @enum {string}
             */
            database: "UP" | "DEGRADED";
            /**
             * @description Judge availability. DEGRADED means the Code Discipline is unavailable; the rest of the site is unaffected.
             * @example UP
             * @enum {string}
             */
            judge: "UP" | "DEGRADED";
            /**
             * @description Running build version
             * @example 0.0.1-SNAPSHOT
             */
            version: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: {
                gmc_recognition?: string;
            };
        };
        requestBody?: never;
        responses: {
            /** @description This browser was already someone, and still is */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["User"];
                };
            };
            /** @description The Unclaimed User that was created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["User"];
                };
            };
        };
    };
    submit: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: {
                gmc_recognition?: string;
            };
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TypingRunSubmission"];
            };
        };
        responses: {
            /** @description The Run as the server computed it */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TypingRun"];
                };
            };
            /** @description This browser is nobody yet */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description The Run was not recorded, and why */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Rejection"];
                };
            };
        };
    };
    submit_1: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: {
                gmc_recognition?: string;
            };
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SolveRunSubmission"];
            };
        };
        responses: {
            /** @description The Solve Run as judged and recorded, whatever the Verdict */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SolveRun"];
                };
            };
            /** @description This browser is nobody yet */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description The Solve Run was not recorded, and why */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Rejection"];
                };
            };
            /** @description There is no Verdict to be had. Only the Code Discipline is affected */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Unjudged"];
                };
            };
        };
    };
    request: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slug: string;
            };
            cookie?: {
                gmc_recognition?: string;
            };
        };
        requestBody?: never;
        responses: {
            /** @description The Challenge, and when it stops being answerable */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SolveChallenge"];
                };
            };
            /** @description This browser is nobody yet — create a User first */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description No activated Pattern has that slug */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    activate: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description What the gate made of each Pattern that was awaiting it */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PatternActivation"][];
                };
            };
        };
    };
    request_1: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: {
                gmc_recognition?: string;
            };
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ChallengeRequest"];
            };
        };
        responses: {
            /** @description The Challenge, and when it stops being answerable */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Challenge"];
                };
            };
            /** @description This browser is nobody yet — create a User first */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description That Discipline has no Passages. Code never will (ADR-0004) */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    me: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: {
                gmc_recognition?: string;
            };
        };
        requestBody?: never;
        responses: {
            /** @description The User this browser is recognised as */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["User"];
                };
            };
            /** @description This browser is nobody yet */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    browse: {
        parameters: {
            query?: {
                /** @description Only this Family */
                family?: "HASH_MAP" | "TWO_POINTERS" | "SLIDING_WINDOW" | "STACK" | "HEAP" | "BINARY_SEARCH" | "GRAPH" | "DYNAMIC_PROGRAMMING";
                /** @description Only this Seniority */
                seniority?: "JUNIOR" | "SENIOR" | "PRINCIPAL";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The Patterns that match */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Pattern"][];
                };
            };
        };
    };
    health: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Every dependency is reachable */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthStatus"];
                };
            };
            /** @description At least one dependency is unreachable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthStatus"];
                };
            };
        };
    };
}
